# Definindo a versão do docker-compose que será utilizada
version: '3.5'

services:
  db:
    container_name: postgres-db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    container_name: python-api
    build: back-end/
    volumes:
      - ./back-end:/api
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  
  app:
    container_name: reactnative-app
    build: front-end/ # será armazenado em cash
    volumes: # criar volumes para poder editar códigos
      - ./front-end:/app
      - /app/node_modules
    ports: 
    - 19000:19000
    - 19001:19001
    - 19002:19002
    - 19006:19006
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - api